// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  fullWidth: string;
  siteContent: string;
  siteNavHeader: string;
  siteNavScrollWrapper: string;
  siteNavWrapper: string;
  siteRoot: string;
  siteWrapper: string;
}
declare var cssExports: CssExports;
export = cssExports;
