// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  externalIcon: string;
  filterButton: string;
  hasActiveChild: string;
  isActive: string;
  isHomePage: string;
  isSubMenu: string;
  link: string;
  links: string;
  matchesFilter: string;
  nav: string;
  navWrapper: string;
  searchBox: string;
  searchBoxWrapper: string;
  section: string;
}
declare var cssExports: CssExports;
export = cssExports;
