// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  androidLogo: string;
  appleLogo: string;
  icon: string;
}
declare var cssExports: CssExports;
export = cssExports;
